services:
  web:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - .:/var/www/html
    ports:
      - 80:80
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always
    depends_on:
      - app
      - mysql
    networks:
      - app-contact
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    environment:
      SERVICE_NAME: app
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html
    networks:
      - app-contact
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./db_data:/var/lib/mysql
    networks:
      - app-contact

networks:
  app-contact:
    driver: bridge